name: Demo pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  buildTest:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build, Test and Analyse
        run: ./gradlew test
